const jsonkeeper = {
  FETCH_REQUEST: 'FETCH_JSONKEEPER_REQUEST',
  FETCH_SUCCESS: 'FETCH_JSONKEEPER_SUCCESS',
  FETCH_FAILURE: 'FETCH_JSONKEEPER_FAILURE',
};
const springcturl = {
  FETCH_SUCCESS: 'FETCH_SPRINGCTURL_SUCCESS',
  FETCH_REQUEST: 'FETCH_SPRINGCTURL_REQUEST',
  FETCH_FAILURE: 'FETCH_SPRINGCTURL_FAILURE',
};
export default {
  jsonkeeper,
  springcturl
};
